# ============================================================
# Trino Users - Password Authentication File
# ============================================================
# Format: username=bcrypt_hashed_password
# Password untuk semua user: password123
# ============================================================

# User: admin (password: password123)
admin=$2b$12$y0QybBq7bXUqMUqFA2uuu.qHoyR.5Yc3mevKvtzdACo28rChI/B.S

# User: metabase (password: password123) - untuk koneksi Metabase
metabase=$2b$12$y0QybBq7bXUqMUqFA2uuu.qHoyR.5Yc3mevKvtzdACo28rChI/B.S